server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 525866

  jpa:
    hibernate:
      ddl-auto: update  # 启动时自动建表
    show-sql: true
    open-in-view: false
